package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.BaseFinance;
import com.tjk.apps.cms.bean.BaseFinanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    long countByExample(BaseFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BaseFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(BaseFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(BaseFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<BaseFinance> selectByExample(BaseFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    BaseFinance selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") BaseFinance record, @Param("example") BaseFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") BaseFinance record, @Param("example") BaseFinanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKeySelective(BaseFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_finance
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKey(BaseFinance record);
}