package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.Basemenu;
import com.tjk.apps.cms.bean.BasemenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasemenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    long countByExample(BasemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BasemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(Basemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(Basemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<Basemenu> selectByExample(BasemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    Basemenu selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Basemenu record, @Param("example") BasemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") Basemenu record, @Param("example") BasemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKeySelective(Basemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKey(Basemenu record);
}