package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.BaseCountract;
import com.tjk.apps.cms.bean.BaseCountractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseCountractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    long countByExample(BaseCountractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BaseCountractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(BaseCountract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(BaseCountract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<BaseCountract> selectByExample(BaseCountractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    BaseCountract selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") BaseCountract record, @Param("example") BaseCountractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") BaseCountract record, @Param("example") BaseCountractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKeySelective(BaseCountract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_countract
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKey(BaseCountract record);
}