package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.Basehouse;
import com.tjk.apps.cms.bean.BasehouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
	
	Basehouse SelectByhouse(int house);
	
    long countByExample(BasehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BasehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(Basehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(Basehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<Basehouse> selectByExample(BasehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    Basehouse selectByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Basehouse record, @Param("example") BasehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") Basehouse record, @Param("example") BasehouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKeySelective(Basehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKey(Basehouse record);
}