package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.Baselmessage;
import com.tjk.apps.cms.bean.BaselmessageExample;
import com.tjk.apps.cms.bean.BaselmessageKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaselmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    long countByExample(BaselmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BaselmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(BaselmessageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(Baselmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(Baselmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<Baselmessage> selectByExample(BaselmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    Baselmessage selectByPrimaryKey(BaselmessageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Baselmessage record, @Param("example") BaselmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") Baselmessage record, @Param("example") BaselmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKeySelective(Baselmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_lmessage
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByPrimaryKey(Baselmessage record);
}