package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.BaseUserRoleExample;
import com.tjk.apps.cms.bean.BaseUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    long countByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(BaseUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(BaseUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(BaseUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<BaseUserRoleKey> selectByExample(BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") BaseUserRoleKey record, @Param("example") BaseUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_role
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") BaseUserRoleKey record, @Param("example") BaseUserRoleExample example);
}