package com.tjk.apps.cms.dao;

import com.tjk.apps.cms.bean.BaseRoleMenuExample;
import com.tjk.apps.cms.bean.BaseRoleMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    long countByExample(BaseRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByExample(BaseRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int deleteByPrimaryKey(BaseRoleMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insert(BaseRoleMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int insertSelective(BaseRoleMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    List<BaseRoleMenuKey> selectByExample(BaseRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") BaseRoleMenuKey record, @Param("example") BaseRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role_menu
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    int updateByExample(@Param("record") BaseRoleMenuKey record, @Param("example") BaseRoleMenuExample example);
}