package com.tjk.apps.cms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Basehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.h_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.DetailedAddress
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String detailedaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.area
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private BigDecimal area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.Orientation
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String orientation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.bulding
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String bulding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.time
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.state
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.owner
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.price
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_house.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.h_id
     *
     * @return the value of s_house.h_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.h_id
     *
     * @param hId the value for s_house.h_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.DetailedAddress
     *
     * @return the value of s_house.DetailedAddress
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getDetailedaddress() {
        return detailedaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.DetailedAddress
     *
     * @param detailedaddress the value for s_house.DetailedAddress
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setDetailedaddress(String detailedaddress) {
        this.detailedaddress = detailedaddress == null ? null : detailedaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.area
     *
     * @return the value of s_house.area
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.area
     *
     * @param area the value for s_house.area
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.Orientation
     *
     * @return the value of s_house.Orientation
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.Orientation
     *
     * @param orientation the value for s_house.Orientation
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setOrientation(String orientation) {
        this.orientation = orientation == null ? null : orientation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.bulding
     *
     * @return the value of s_house.bulding
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getBulding() {
        return bulding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.bulding
     *
     * @param bulding the value for s_house.bulding
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setBulding(String bulding) {
        this.bulding = bulding == null ? null : bulding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.time
     *
     * @return the value of s_house.time
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.time
     *
     * @param time the value for s_house.time
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.state
     *
     * @return the value of s_house.state
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.state
     *
     * @param state the value for s_house.state
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.owner
     *
     * @return the value of s_house.owner
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.owner
     *
     * @param owner the value for s_house.owner
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.price
     *
     * @return the value of s_house.price
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.price
     *
     * @param price the value for s_house.price
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_house.url
     *
     * @return the value of s_house.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_house.url
     *
     * @param url the value for s_house.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}