package com.tjk.apps.cms.bean;

public class Basemenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.m_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.menuname
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String menuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.pid
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_menu.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.m_id
     *
     * @return the value of s_menu.m_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.m_id
     *
     * @param mId the value for s_menu.m_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.menuname
     *
     * @return the value of s_menu.menuname
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.menuname
     *
     * @param menuname the value for s_menu.menuname
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.pid
     *
     * @return the value of s_menu.pid
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.pid
     *
     * @param pid the value for s_menu.pid
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_menu.url
     *
     * @return the value of s_menu.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_menu.url
     *
     * @param url the value for s_menu.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}