package com.tjk.apps.cms.bean;

public class BaseRoleMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_menu.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role_menu.m_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer mId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_menu.r_id
     *
     * @return the value of s_role_menu.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_menu.r_id
     *
     * @param rId the value for s_role_menu.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role_menu.m_id
     *
     * @return the value of s_role_menu.m_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role_menu.m_id
     *
     * @param mId the value for s_role_menu.m_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }
}