package com.tjk.apps.cms.bean;

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.Future;
import javax.validation.constraints.Min;
import javax.validation.constraints.Past;

public class BaseCountract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.c_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.DateOfHire
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Past(message="起租日期必须是过去日期")
    private Date dateofhire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.NoRentDate
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Future(message="止租日期必须是未来日期")
    private Date norentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.ower
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer ower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.Customer
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer house;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.MonthlyRent
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Min(value=0,message="月租必须大于零")
    private BigDecimal monthlyrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.Total
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Min(value=0,message="月租总额必须大于零")
    private BigDecimal total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.committime
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Date committime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_countract.Remarks
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.c_id
     *
     * @return the value of s_countract.c_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.c_id
     *
     * @param cId the value for s_countract.c_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.DateOfHire
     *
     * @return the value of s_countract.DateOfHire
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getDateofhire() {
        return dateofhire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.DateOfHire
     *
     * @param dateofhire the value for s_countract.DateOfHire
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setDateofhire(Date dateofhire) {
        this.dateofhire = dateofhire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.NoRentDate
     *
     * @return the value of s_countract.NoRentDate
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getNorentdate() {
        return norentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.NoRentDate
     *
     * @param norentdate the value for s_countract.NoRentDate
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setNorentdate(Date norentdate) {
        this.norentdate = norentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.ower
     *
     * @return the value of s_countract.ower
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getOwer() {
        return ower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.ower
     *
     * @param ower the value for s_countract.ower
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setOwer(Integer ower) {
        this.ower = ower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.Customer
     *
     * @return the value of s_countract.Customer
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.Customer
     *
     * @param customer the value for s_countract.Customer
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setCustomer(Integer customer) {
        this.customer = customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.house
     *
     * @return the value of s_countract.house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.house
     *
     * @param house the value for s_countract.house
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setHouse(Integer house) {
        this.house = house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.MonthlyRent
     *
     * @return the value of s_countract.MonthlyRent
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public BigDecimal getMonthlyrent() {
        return monthlyrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.MonthlyRent
     *
     * @param monthlyrent the value for s_countract.MonthlyRent
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setMonthlyrent(BigDecimal monthlyrent) {
        this.monthlyrent = monthlyrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.Total
     *
     * @return the value of s_countract.Total
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.Total
     *
     * @param total the value for s_countract.Total
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.committime
     *
     * @return the value of s_countract.committime
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getCommittime() {
        return committime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.committime
     *
     * @param committime the value for s_countract.committime
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setCommittime(Date committime) {
        this.committime = committime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_countract.Remarks
     *
     * @return the value of s_countract.Remarks
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_countract.Remarks
     *
     * @param remarks the value for s_countract.Remarks
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}