package com.tjk.apps.cms.bean;

import java.util.Date;

public class Baselmessage extends BaselmessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_lmessage.comment
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_lmessage.registration
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Date registration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_lmessage.comment
     *
     * @return the value of s_lmessage.comment
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_lmessage.comment
     *
     * @param comment the value for s_lmessage.comment
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_lmessage.registration
     *
     * @return the value of s_lmessage.registration
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getRegistration() {
        return registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_lmessage.registration
     *
     * @param registration the value for s_lmessage.registration
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setRegistration(Date registration) {
        this.registration = registration;
    }
}