package com.tjk.apps.cms.bean;

public class BaseUserRoleKey {
	
    public BaseUserRoleKey(Integer uId, Integer rId) {
		super();
		this.uId = uId;
		this.rId = rId;
	}

	public BaseUserRoleKey() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.u_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_role.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.u_id
     *
     * @return the value of s_user_role.u_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.u_id
     *
     * @param uId the value for s_user_role.u_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user_role.r_id
     *
     * @return the value of s_user_role.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_role.r_id
     *
     * @param rId the value for s_user_role.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }
}