package com.tjk.apps.cms.bean;

import java.math.BigDecimal;
import java.util.Date;

public class BaseFinance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.f_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.ordernumber
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.number
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private BigDecimal number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.payway
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer payway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.payitem
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String payitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.Originator
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer originator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.paypeople
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer paypeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.supplier
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_finance.time
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.f_id
     *
     * @return the value of s_finance.f_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.f_id
     *
     * @param fId the value for s_finance.f_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.ordernumber
     *
     * @return the value of s_finance.ordernumber
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.ordernumber
     *
     * @param ordernumber the value for s_finance.ordernumber
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber == null ? null : ordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.number
     *
     * @return the value of s_finance.number
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.number
     *
     * @param number the value for s_finance.number
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.payway
     *
     * @return the value of s_finance.payway
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.payway
     *
     * @param payway the value for s_finance.payway
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPayway(Integer payway) {
        this.payway = payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.payitem
     *
     * @return the value of s_finance.payitem
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getPayitem() {
        return payitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.payitem
     *
     * @param payitem the value for s_finance.payitem
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPayitem(String payitem) {
        this.payitem = payitem == null ? null : payitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.Originator
     *
     * @return the value of s_finance.Originator
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getOriginator() {
        return originator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.Originator
     *
     * @param originator the value for s_finance.Originator
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setOriginator(Integer originator) {
        this.originator = originator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.paypeople
     *
     * @return the value of s_finance.paypeople
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getPaypeople() {
        return paypeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.paypeople
     *
     * @param paypeople the value for s_finance.paypeople
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPaypeople(Integer paypeople) {
        this.paypeople = paypeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.supplier
     *
     * @return the value of s_finance.supplier
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.supplier
     *
     * @param supplier the value for s_finance.supplier
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setSupplier(Integer supplier) {
        this.supplier = supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_finance.time
     *
     * @return the value of s_finance.time
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_finance.time
     *
     * @param time the value for s_finance.time
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}