package com.tjk.apps.cms.bean;

public class BaseRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.rolename
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.r_id
     *
     * @return the value of s_role.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.r_id
     *
     * @param rId the value for s_role.r_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.rolename
     *
     * @return the value of s_role.rolename
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.rolename
     *
     * @param rolename the value for s_role.rolename
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}