package com.tjk.apps.cms.bean;

public class BaselmessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_lmessage.my
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer my;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_lmessage.other
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_lmessage.my
     *
     * @return the value of s_lmessage.my
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getMy() {
        return my;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_lmessage.my
     *
     * @param my the value for s_lmessage.my
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setMy(Integer my) {
        this.my = my;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_lmessage.other
     *
     * @return the value of s_lmessage.other
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_lmessage.other
     *
     * @param other the value for s_lmessage.other
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setOther(Integer other) {
        this.other = other;
    }
}