package com.tjk.apps.cms.bean;

import java.util.Date;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Length;

import io.swagger.annotations.ApiModelProperty;

public class BaseUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.u_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.count
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @ApiModelProperty(value="账号")
    @NotEmpty(message="账号不能为空")
    @Length(min=6,max=6 ,message="账号的长度必须为六")
    private String count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @ApiModelProperty(value="密码账号")
    @NotEmpty(message="密码账号不能为空")
    @Length(max=8,message="账号的长度必须不能超过8位数")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.name
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @ApiModelProperty(value="姓名")
    @NotEmpty(message="姓名不能为空")
    @Length(max=10 ,message="姓名的长度不能超过10")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.gender
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Pattern(regexp = "[Male|Female]", message = "性别只能在男或女中选择！")
    @ApiModelProperty(value = "性别")
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.phone
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Pattern(regexp="^[1][3,4,5,7,8][0-9]{9}$",message="电话格式错误")
    @ApiModelProperty(value = "移动电话") 
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.registration
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private Date registration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.age
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Digits(integer = 18, fraction = 140, message = "年龄必须在18-140之间！")
    @ApiModelProperty(value = "年龄")
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.address
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.IDCardNumber
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    @Pattern(regexp="^\\d{15}|\\d{18}$",message="身份号证验证出错")
    @ApiModelProperty(value = "身份证号") 
    private String idcardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.u_id
     *
     * @return the value of s_user.u_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.u_id
     *
     * @param uId the value for s_user.u_id
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.count
     *
     * @return the value of s_user.count
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.count
     *
     * @param count the value for s_user.count
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.name
     *
     * @return the value of s_user.name
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.name
     *
     * @param name the value for s_user.name
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.gender
     *
     * @return the value of s_user.gender
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.gender
     *
     * @param gender the value for s_user.gender
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.phone
     *
     * @return the value of s_user.phone
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.phone
     *
     * @param phone the value for s_user.phone
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.registration
     *
     * @return the value of s_user.registration
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Date getRegistration() {
        return registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.registration
     *
     * @param registration the value for s_user.registration
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setRegistration(Date registration) {
        this.registration = registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.age
     *
     * @return the value of s_user.age
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.age
     *
     * @param age the value for s_user.age
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.address
     *
     * @return the value of s_user.address
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.address
     *
     * @param address the value for s_user.address
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.IDCardNumber
     *
     * @return the value of s_user.IDCardNumber
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getIdcardnumber() {
        return idcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.IDCardNumber
     *
     * @param idcardnumber the value for s_user.IDCardNumber
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setIdcardnumber(String idcardnumber) {
        this.idcardnumber = idcardnumber == null ? null : idcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.url
     *
     * @return the value of s_user.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.url
     *
     * @param url the value for s_user.url
     *
     * @mbg.generated Mon Apr 20 23:59:13 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}